blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/tak/policy-checker/discussions/new?category=q-a
    about: Ask and answer questions here.
  - name: Request a feature
    url: https://github.com/tak/policy-checker/discussions/new?category=ideas
    about: Share ideas for new features.
  - name_security: Report a security issue
    url: https://github.com/tak/policy-checker/security/policy
    about: Learn how to notify us of a security issue.
